### PR TITLE
Validation & Api results handling.

### PR DESCRIPTION
**Pull request by Hephaestots**
Little bit of Api/Application code for Validation and Results.
Changes in the draw.io of the class UML.

### CODE REVIEW

**Review by Super0silveR — APPROVED** [review]
Looks good

**Comment by YounesAnys** [comment]
looks good

**Review by Super0silveR — APPROVED** [review]

**Review by YounesAnys — APPROVED** [review]

**Review by Super0silveR — APPROVED** [review]
test

**Review by YounesAnys — APPROVED** [review]

**Review by Super0silveR — APPROVED** [review]
test

**Review by YounesAnys — APPROVED** [review]

**Review by YounesAnys — APPROVED** [review]

**Pull request merged**
